functionsDirectory = "C:\\Users\\Nora\\Desktop\\Educate\\UCAT-ukmla\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "C:\\Users\\Nora\\Desktop\\Educate\\UCAT-ukmla\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "vite build"
functions = "C:\\Users\\Nora\\Desktop\\Educate\\UCAT-ukmla\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[dev]
command = "npm run dev"
targetPort = 5173.0
port = 8888.0
framework = "#custom"
autoLaunch = false

[functions]

[functions."*"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]