[build]
  command = "vite build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  framework = "#custom"
  autoLaunch = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
