-- Plan 14 — fill the under-served topics so chip drilling actually works.
--
-- Bank state before this migration (default-visible, exam='UKMLA'):
--   Cardiology+Cardiovascular: 18  | Calculations: 26
--   Gastroenterology: 8 | Neurology: 8 | Renal: 5 | Haematology: 5
--   Infection: 5 | Surgery+Ortho: 6 | Respiratory: 3 | Psychiatry: 3
--   Dermatology: 3 | Obstetrics: 3 | Endocrinology: 3 | Paediatrics: 3
--   Immunology: 2
--
-- The 3-atom topics make filtered drilling useless ("3 question pool, you've
-- seen them all"). Add ~6 SBAs per under-served topic to bring them to ~9.
-- All hand-authored, NICE/BNF/Resus-cited, doctor_seed source_type so they
-- show up under the default toggle without the AI-draft warning.

insert into public.atoms (
  exam, topic_path, claim, canonical_stem, answer, distractors,
  difficulty, image_url, image_alt,
  citation_url, citation_label, source_type,
  high_yield, free_tier, status, question_kind, source_concept_id
)
select * from (values
  -- ============= RESPIRATORY (was 3, +6 → 9) =============
  ('UKMLA', ARRAY['Respiratory','CAP'],
   'CURB-65 score: confusion, urea >7, RR ≥30, BP <90/60, age ≥65. Score ≥3 → consider HDU.',
   'A 72-year-old woman with cough and fever. RR 32, BP 86/54, urea 9, AMTS 7/10. Which inpatient setting is most appropriate?',
   'HDU/ICU referral',
   '["Discharge with oral amoxicillin","Ward-level admission with oral antibiotics","Ward-level with IV co-amoxiclav only","Outpatient antibiotics + GP review in 48 h"]'::jsonb,
   2, null, null, 'https://www.nice.org.uk/guidance/cg191', 'NICE CG191 — Pneumonia', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-resp-curb-1'),
  ('UKMLA', ARRAY['Respiratory','COPD'],
   'COPD exacerbation: controlled O2 (88-92 % target), nebulised bronchodilators, oral pred 30 mg × 5 d, antibiotics if purulent sputum.',
   'A 68-year-old man with COPD presents with increased breathlessness and purulent sputum. SpO₂ 86 % on air. Initial management?',
   'Controlled O2 to 88-92 %, salbutamol/ipratropium nebs, oral prednisolone 30 mg, oral amoxicillin',
   '["High-flow O2 to >94 %, IV amoxicillin only","Salbutamol nebs alone, observe for 2 h","Oral prednisolone alone, no antibiotics","Continuous BIPAP without bronchodilators"]'::jsonb,
   2, null, null, 'https://www.nice.org.uk/guidance/ng115', 'NICE NG115 — COPD', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-resp-copd-mx'),
  ('UKMLA', ARRAY['Respiratory','PE'],
   'Wells score >4 → CTPA. ≤4 with positive D-dimer → CTPA. ≤4 with negative D-dimer → PE excluded.',
   'A 38-year-old woman 2 weeks post-op presents with pleuritic chest pain and dyspnoea. Wells score = 6. Which is the next step?',
   'CT pulmonary angiogram',
   '["D-dimer first; CTPA only if positive","V/Q scan first regardless of pregnancy status","Therapeutic warfarin without imaging","Discharge — Wells alone is not actionable"]'::jsonb,
   2, null, null, 'https://www.nice.org.uk/guidance/ng158', 'NICE NG158 — VTE diagnosis', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-resp-pe-wells'),
  ('UKMLA', ARRAY['Respiratory','Asthma'],
   'BTS/SIGN acute asthma: any SpO₂ <92 %, PEFR <33 % best, silent chest, exhaustion, altered consciousness = life-threatening.',
   'A 28-year-old with asthma is brought in unable to complete sentences. SpO₂ 89 % on air, PEFR 30 % of best. Which severity band?',
   'Life-threatening asthma',
   '["Mild exacerbation","Moderate exacerbation","Acute severe asthma","Near-fatal asthma"]'::jsonb,
   2, null, null, 'https://www.brit-thoracic.org.uk/quality-improvement/guidelines/asthma/', 'BTS/SIGN — Asthma', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-resp-asthma-severity'),
  ('UKMLA', ARRAY['Respiratory','Lung cancer'],
   'NICE NG12: persistent unexplained cough/haemoptysis ≥3 weeks in >40 yo → urgent CXR within 2 weeks.',
   'A 62-year-old smoker has had a cough for 4 weeks plus one episode of haemoptysis. Most appropriate next step?',
   'Urgent chest X-ray within 2 weeks (2-week wait pathway)',
   '["Reassure and review in 6 weeks","CT thorax-abdomen-pelvis as first investigation","Bronchoscopy directly","Trial of oral amoxicillin and review in 4 weeks"]'::jsonb,
   1, null, null, 'https://www.nice.org.uk/guidance/ng12', 'NICE NG12 — Suspected cancer', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-resp-lung-ca-cxr'),
  ('UKMLA', ARRAY['Respiratory','Pneumothorax'],
   'Primary spontaneous pneumothorax >2 cm at hilum or symptomatic → aspiration; if fails, chest drain.',
   'A 22-year-old tall male has sudden-onset right-sided chest pain. CXR shows a 3 cm primary pneumothorax. He is dyspnoeic. Initial management?',
   'Needle aspiration in the second intercostal space, midclavicular line',
   '["Discharge with analgesia, repeat CXR in 1 week","Immediate chest drain insertion","High-flow oxygen alone","CT thorax then re-image in 24 h"]'::jsonb,
   3, null, null, 'https://www.brit-thoracic.org.uk/quality-improvement/guidelines/pleural-disease/', 'BTS — Pleural disease', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-resp-pneumothorax'),

  -- ============= ENDOCRINOLOGY (was 3, +6 → 9) =============
  ('UKMLA', ARRAY['Endocrinology','T2DM'],
   'NICE NG28: T2DM step-up — metformin first-line; add SGLT2i if CV/renal benefit; further escalation thereafter.',
   'A 56-year-old with T2DM, BMI 32, eGFR 80, established cardiovascular disease. HbA1c 62 mmol/mol on metformin. Best add-on?',
   'SGLT2 inhibitor (e.g. empagliflozin)',
   '["DPP-4 inhibitor (e.g. sitagliptin)","Sulfonylurea (e.g. gliclazide)","Pioglitazone","Switch to insulin glargine"]'::jsonb,
   2, null, null, 'https://www.nice.org.uk/guidance/ng28', 'NICE NG28 — Type 2 diabetes', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-endo-t2dm-sglt2'),
  ('UKMLA', ARRAY['Endocrinology','Hypothyroidism'],
   'Primary hypothyroidism: high TSH + low free T4. Treat with levothyroxine; start lower in elderly/IHD (25 mcg).',
   'A 76-year-old man with ischaemic heart disease has TSH 28 mU/L, free T4 7 pmol/L (low). Most appropriate starting dose of levothyroxine?',
   '25 micrograms once daily',
   '["100 micrograms once daily","200 micrograms once daily","No treatment — repeat TSH in 3 months","T3 (liothyronine) 20 mcg"]'::jsonb,
   2, null, null, 'https://www.nice.org.uk/guidance/ng145', 'NICE NG145 — Thyroid disease', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-endo-hypothyroid-elderly'),
  ('UKMLA', ARRAY['Endocrinology','Addison'],
   'Addisonian crisis: hypotension + hyponatraemia + hyperkalaemia + hypoglycaemia. Treat IV hydrocortisone 100 mg + IV 0.9 % saline.',
   'A 35-year-old with known Addison''s presents with vomiting, BP 80/50, Na 128, K 5.9, glucose 3.1. Immediate management?',
   'IV hydrocortisone 100 mg + IV 0.9 % saline',
   '["IV insulin + dextrose","Oral hydrocortisone double-dose","IV fludrocortisone alone","IV calcium gluconate 10 ml of 10 %"]'::jsonb,
   2, null, null, 'https://cks.nice.org.uk/topics/addisons-disease/', 'NICE CKS — Addison''s disease', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-endo-addisonian'),
  ('UKMLA', ARRAY['Endocrinology','Hyperthyroidism'],
   'Graves'' disease: anti-TSH receptor antibody positive, smooth diffuse goitre, eye signs. First-line: carbimazole + β-blocker for symptoms.',
   'A 32-year-old woman has weight loss, palpitations, exophthalmos. TSH suppressed, free T4 raised, anti-TSHR antibodies positive. First-line drug therapy?',
   'Carbimazole + propranolol',
   '["Levothyroxine + propranolol","Radioactive iodine immediately","Total thyroidectomy without medical pre-treatment","Lithium + carbimazole"]'::jsonb,
   2, null, null, 'https://cks.nice.org.uk/topics/hyperthyroidism/', 'NICE CKS — Hyperthyroidism', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-endo-graves-mx'),
  ('UKMLA', ARRAY['Endocrinology','DKA'],
   'DKA dx triad (JBDS): glucose >11, ketones ≥3, pH <7.30 OR HCO₃ <15.',
   'A 19-year-old type 1 diabetic with vomiting. Glucose 24 mmol/L, ketones 4.2, pH 7.22. Which finding clinches DKA over HHS?',
   'Significant ketonaemia (≥3) with acidosis',
   '["Hyperglycaemia alone","Hyperosmolar serum (>320 mOsm/kg)","Slow onset over weeks","Absence of acidosis"]'::jsonb,
   2, null, null, 'https://www.diabetes.org.uk/joint-british-diabetes-societies', 'JBDS — DKA management', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-endo-dka-vs-hhs'),
  ('UKMLA', ARRAY['Endocrinology','Hypoglycaemia'],
   'Severe hypoglycaemia (unable to swallow): IV 10 % dextrose 100-200 ml or IM glucagon 1 mg.',
   'A 25-year-old with type 1 diabetes is found unconscious. Capillary glucose 1.8 mmol/L. No IV access yet. Most appropriate immediate step?',
   'IM glucagon 1 mg',
   '["Oral glucose gel under the tongue","IV insulin to stabilise","IV 50 % dextrose 50 ml","Wait for paramedics — no action"]'::jsonb,
   1, null, null, 'https://www.nice.org.uk/guidance/ng17', 'NICE NG17 — Type 1 diabetes', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-endo-hypo-im'),

  -- ============= PAEDIATRICS (was 3, +6 → 9) =============
  ('UKMLA', ARRAY['Paediatrics','Bronchiolitis'],
   'Bronchiolitis: <2 yrs, RSV, cough/wheeze + crackles + feeding difficulty. Supportive only — no salbutamol/abx/steroids.',
   'A 4-month-old has bronchiolitis. SpO₂ 91 %, feeding 60 % of normal. Most appropriate management?',
   'Admit for supportive care: oxygen, NG/IV fluids, monitor',
   '["Salbutamol nebulisers","Oral amoxicillin and discharge","Oral prednisolone","Discharge with safety-netting only"]'::jsonb,
   1, null, null, 'https://www.nice.org.uk/guidance/ng9', 'NICE NG9 — Bronchiolitis', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-paeds-bronchiolitis-mx'),
  ('UKMLA', ARRAY['Paediatrics','UTI'],
   'NICE NG224: UTI in <3 mo — urgent paediatric assessment + IV antibiotics. Send urine via clean catch.',
   'A 6-week-old has fever and poor feeding. Urine dip positive for nitrites and leucocytes. Most appropriate next step?',
   'Refer urgently to paediatrics for IV antibiotics',
   '["Oral co-amoxiclav and review in 48 h","Reassure and review with GP in 1 week","Outpatient renal USS first","Trimethoprim 3-day course at home"]'::jsonb,
   2, null, null, 'https://www.nice.org.uk/guidance/ng224', 'NICE NG224 — UTI in under 16s', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-paeds-uti-young-infant'),
  ('UKMLA', ARRAY['Paediatrics','Croup'],
   'Croup: barking cough + stridor + hoarseness, viral; mild/moderate → single oral dexamethasone 0.15 mg/kg.',
   'A 2-year-old has a barking cough and stridor at rest. No drooling, alert. Most appropriate first treatment?',
   'Single oral dose of dexamethasone 0.15 mg/kg',
   '["Nebulised salbutamol","IV ceftriaxone","Intubation immediately","Oral amoxicillin"]'::jsonb,
   1, null, null, 'https://cks.nice.org.uk/topics/croup/', 'NICE CKS — Croup', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-paeds-croup'),
  ('UKMLA', ARRAY['Paediatrics','Sepsis'],
   'Paediatric sepsis red flags: cap refill ≥3 s, mottled skin, tachycardia/tachypnoea by age, altered behaviour, non-blanching rash.',
   'A 3-year-old has fever, mottled skin, cap refill 4 s, HR 170, RR 50. Most appropriate first action?',
   'Activate the paediatric sepsis pathway: bloods + blood cultures + IV broad-spectrum antibiotics within 1 h',
   '["Antipyretics and review in 1 h","Oral co-amoxiclav and reassure","CT head before any further action","High-flow oxygen alone"]'::jsonb,
   1, null, null, 'https://www.nice.org.uk/guidance/ng51', 'NICE NG51 — Sepsis', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-paeds-sepsis-pathway'),
  ('UKMLA', ARRAY['Paediatrics','Wheeze'],
   'Viral-induced wheeze: pre-school child with viral URTI + episodic wheeze. Salbutamol via spacer first-line.',
   'A 3-year-old with a coryzal illness develops audible wheeze. Mild work of breathing, SpO₂ 95 %. First-line treatment?',
   'Salbutamol via spacer, 2-10 puffs as needed',
   '["IV hydrocortisone","Oral amoxicillin","Continuous nebulised salbutamol","Reassure — no treatment indicated"]'::jsonb,
   2, null, null, 'https://cks.nice.org.uk/topics/wheeze-in-children/', 'NICE CKS — Wheeze in children', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-paeds-viral-wheeze'),
  ('UKMLA', ARRAY['Paediatrics','Immunisation'],
   'Routine UK schedule: at 8 weeks first DTaP/IPV/Hib/HepB + Men B + rotavirus + 13-valent pneumococcal.',
   'At which age is the first dose of DTaP/IPV/Hib/HepB given in the UK schedule?',
   '8 weeks',
   '["Birth","12 weeks","6 months","12 months"]'::jsonb,
   1, null, null, 'https://www.gov.uk/government/publications/the-complete-routine-immunisation-schedule', 'UK Routine Immunisation Schedule', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-paeds-imms-8w'),

  -- ============= PSYCHIATRY (was 3, +6 → 9) =============
  ('UKMLA', ARRAY['Psychiatry','Depression'],
   'NICE NG222: moderate-severe depression → CBT + SSRI (sertraline first line in adults).',
   'A 32-year-old has 8 weeks of low mood, anhedonia, insomnia, and PHQ-9 of 17. Most appropriate first-line treatment?',
   'Sertraline + offer CBT',
   '["Olanzapine","Lorazepam PRN","Lithium monotherapy","Watchful waiting for 6 months"]'::jsonb,
   2, null, null, 'https://www.nice.org.uk/guidance/ng222', 'NICE NG222 — Depression in adults', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-psych-depression-firstline'),
  ('UKMLA', ARRAY['Psychiatry','Mania'],
   'Acute mania in bipolar: oral antipsychotic (haloperidol/olanzapine/risperidone/quetiapine) first-line; add lithium for relapse prevention.',
   'A 28-year-old with bipolar disorder is in an acute manic episode — grandiose, reduced sleep, pressured speech. First-line drug?',
   'Oral antipsychotic (e.g. olanzapine)',
   '["Lithium monotherapy as immediate treatment","SSRI","Long-acting depot benzodiazepine","Clozapine"]'::jsonb,
   2, null, null, 'https://www.nice.org.uk/guidance/cg185', 'NICE CG185 — Bipolar disorder', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-psych-mania-acute'),
  ('UKMLA', ARRAY['Psychiatry','Suicide risk'],
   'Acute high-risk suicidal ideation with plan and means: same-day psychiatric assessment, consider Mental Health Act if not consenting.',
   'A patient discloses active suicidal plan with stockpiled medication and clear intent today. Most appropriate immediate management?',
   'Same-day psychiatric assessment; remove means; admit (informally if consenting, MHA if not)',
   '["Routine outpatient psychiatry referral within 4 weeks","Discharge with crisis-line phone number","Start sertraline and review in 2 weeks","Mental Health Act detention without assessment"]'::jsonb,
   2, null, null, 'https://www.nice.org.uk/guidance/cg133', 'NICE CG133 — Self-harm', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-psych-suicide-acute'),
  ('UKMLA', ARRAY['Psychiatry','Anxiety'],
   'Generalised anxiety disorder: sertraline first-line SSRI; offer CBT or applied relaxation as evidence-based psychological therapy.',
   'A 40-year-old has 6 months of free-floating anxiety, worry, sleep disturbance. GAD-7 = 14. Most appropriate first-line treatment?',
   'Sertraline + low-intensity CBT',
   '["Diazepam regularly","Beta-blocker monotherapy","Tricyclic antidepressant","Watchful waiting"]'::jsonb,
   2, null, null, 'https://www.nice.org.uk/guidance/cg113', 'NICE CG113 — GAD', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-psych-gad-firstline'),
  ('UKMLA', ARRAY['Psychiatry','Eating disorders'],
   'Anorexia nervosa: adult/adolescent first-line = anorexia-focused family therapy (under-18) or individual eating-disorder-focused CBT (adult).',
   'A 16-year-old with anorexia nervosa, BMI 16. First-line psychological therapy?',
   'Anorexia-focused family therapy',
   '["EMDR","Mindfulness-based stress reduction","Acceptance and commitment therapy","Lithium augmentation"]'::jsonb,
   3, null, null, 'https://www.nice.org.uk/guidance/ng69', 'NICE NG69 — Eating disorders', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-psych-anorexia-fft'),
  ('UKMLA', ARRAY['Psychiatry','Delirium'],
   'Delirium: identify and treat the cause; non-pharm (lights, orientation, family) first; haloperidol or olanzapine if severe agitation.',
   'A 78-year-old post-op patient is acutely confused and agitated, pulling at lines. Non-pharm measures already tried. Most appropriate next step?',
   'Low-dose haloperidol 0.5-1 mg PO/IM',
   '["Diazepam 10 mg IV","Quetiapine 100 mg STAT","Restraints without medication","Wait it out — delirium resolves spontaneously"]'::jsonb,
   2, null, null, 'https://www.nice.org.uk/guidance/cg103', 'NICE CG103 — Delirium', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-psych-delirium-haloperidol'),

  -- ============= DERMATOLOGY (was 3, +6 → 9) =============
  ('UKMLA', ARRAY['Dermatology','Melanoma'],
   'ABCDE — Asymmetry, Border irregular, Colour variation, Diameter >6 mm, Evolution. Any → 2-week-wait dermatology.',
   'A 55-year-old has a pigmented lesion on her back: asymmetric, irregular border, multiple shades, 8 mm. Most appropriate next step?',
   'Urgent 2-week-wait dermatology referral',
   '["Routine GP review in 6 weeks","Cryotherapy in primary care","Topical fluorouracil","Reassure — small lesions never melanoma"]'::jsonb,
   1, null, null, 'https://www.nice.org.uk/guidance/ng12', 'NICE NG12 — Suspected cancer', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-derm-melanoma-ww'),
  ('UKMLA', ARRAY['Dermatology','Eczema'],
   'Atopic eczema management ladder: emollients > topical steroid potency-matched to severity > calcineurin inhibitors > phototherapy/systemic.',
   'A 6-year-old has moderate eczema on flexures despite regular emollient. Most appropriate next step?',
   'Add a moderate-potency topical corticosteroid (e.g. clobetasone)',
   '["Topical clobetasol propionate 0.05 % (very potent)","Oral methotrexate","Phototherapy","Stop emollient and observe"]'::jsonb,
   2, null, null, 'https://www.nice.org.uk/guidance/cg57', 'NICE CG57 — Atopic eczema', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-derm-eczema-ladder'),
  ('UKMLA', ARRAY['Dermatology','Psoriasis'],
   'Psoriasis ladder: emollient + potent topical steroid + vitamin D analogue → coal tar/dithranol → phototherapy → systemic/biologic.',
   'A 35-year-old has chronic plaque psoriasis on extensor surfaces. First-line topical regimen?',
   'Emollient + potent topical corticosteroid + topical vitamin D analogue (e.g. calcipotriol)',
   '["Oral methotrexate as first-line","Phototherapy as first-line","Topical antifungal","Avoid all moisturisers"]'::jsonb,
   2, null, null, 'https://www.nice.org.uk/guidance/cg153', 'NICE CG153 — Psoriasis', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-derm-psoriasis-topical'),
  ('UKMLA', ARRAY['Dermatology','Acne'],
   'Acne moderate-severe: 12-week course of fixed combination topical (e.g. adapalene + benzoyl peroxide) ± oral antibiotic (lymecycline/doxycycline) per NICE NG198.',
   'A 17-year-old has moderate acne with inflammatory papules and pustules. Most appropriate first-line treatment?',
   '12-week course of topical adapalene + benzoyl peroxide ± oral lymecycline',
   '["Isotretinoin as first-line","Topical antifungal","Oral prednisolone","Cryotherapy"]'::jsonb,
   2, null, null, 'https://www.nice.org.uk/guidance/ng198', 'NICE NG198 — Acne vulgaris', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-derm-acne-firstline'),
  ('UKMLA', ARRAY['Dermatology','SJS'],
   'Stevens-Johnson syndrome: drug reaction, mucosal involvement, target lesions, <10 % BSA detachment. Stop the offending drug; admit; specialist care.',
   'A 30-year-old develops mucosal ulcers, target lesions, and 5 % skin detachment 2 weeks after starting allopurinol. Most appropriate management?',
   'Stop allopurinol; admit; refer to dermatology/burns specialist',
   '["Continue allopurinol; trial topical steroid","Systemic steroid as outpatient","Reassure and review in 1 week","Methotrexate"]'::jsonb,
   3, null, null, 'https://patient.info/doctor/stevens-johnson-syndrome', 'BAD — SJS guidance', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-derm-sjs-stop-drug'),
  ('UKMLA', ARRAY['Dermatology','Urticaria'],
   'Acute urticaria: H1 antihistamine (e.g. cetirizine) — non-sedating, second-generation. Adrenaline only if anaphylaxis.',
   'A 25-year-old has hives and itch after eating shellfish. No tongue swelling, no breathing difficulty, normal BP. First-line?',
   'Oral cetirizine 10 mg',
   '["IM adrenaline 500 micrograms","IV hydrocortisone 200 mg","Topical hydrocortisone alone","Diphenhydramine IM"]'::jsonb,
   1, null, null, 'https://cks.nice.org.uk/topics/urticaria/', 'NICE CKS — Urticaria', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-derm-urticaria-cetirizine'),

  -- ============= OBSTETRICS (was 3, +6 → 9) =============
  ('UKMLA', ARRAY['Obstetrics','Pre-natal'],
   'Pre-conception folic acid: 400 mcg daily. 5 mg if previous NTD-affected pregnancy, diabetes, or BMI ≥30.',
   'A 28-year-old planning pregnancy has BMI 33. Most appropriate folic acid dose?',
   '5 mg daily',
   '["No supplementation needed","100 mcg daily","400 mcg daily","10 mg daily"]'::jsonb,
   2, null, null, 'https://cks.nice.org.uk/topics/pre-conception-advice-and-management/', 'NICE CKS — Pre-conception advice', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-obs-folic-bmi'),
  ('UKMLA', ARRAY['Obstetrics','GDM'],
   'Gestational diabetes screen: OGTT at 24-28 weeks if any risk factor. Diagnostic if fasting ≥5.6 or 2-h ≥7.8.',
   'A 32-year-old at 26/40 has fasting plasma glucose 5.8 mmol/L on OGTT. Most appropriate first-line management?',
   'Diet and exercise advice; review fasting glucose in 1-2 weeks; metformin if targets not met',
   '["Immediate insulin","No further action — OGTT is normal","Glibenclamide","Repeat OGTT at 36 weeks regardless"]'::jsonb,
   2, null, null, 'https://www.nice.org.uk/guidance/ng3', 'NICE NG3 — Diabetes in pregnancy', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-obs-gdm-firstline'),
  ('UKMLA', ARRAY['Obstetrics','PPH'],
   'Primary PPH (>500 ml within 24 h of vaginal delivery / 1000 ml after C-section): 4 T''s — Tone, Trauma, Tissue, Thrombin. First-line: bimanual compression + uterotonics (oxytocin).',
   'A patient haemorrhages 800 ml immediately after vaginal delivery. Uterus feels boggy. First-line management?',
   'Uterine massage + IV oxytocin',
   '["IV tranexamic acid alone","Wait for 5 minutes — usually self-resolves","Manual perineal repair only","Hysterectomy"]'::jsonb,
   2, null, null, 'https://www.rcog.org.uk/media/3hbhkdwr/gtg-52.pdf', 'RCOG GTG 52 — PPH', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-obs-pph-firstline'),
  ('UKMLA', ARRAY['Obstetrics','Pre-eclampsia'],
   'Pre-eclampsia: BP ≥140/90 + proteinuria ≥20 weeks. Severe = BP ≥160/110 OR organ dysfunction. Mg sulfate for severe + eclampsia prophylaxis.',
   'A 30-week primigravida with BP 168/112, proteinuria 3+, headache. Most appropriate immediate management?',
   'IV labetalol + IV magnesium sulfate + admit',
   '["Oral methyldopa and home review in 1 week","Diuretic","Reassure and review in 48 h","IV diazepam"]'::jsonb,
   2, null, null, 'https://www.nice.org.uk/guidance/ng133', 'NICE NG133 — Hypertension in pregnancy', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-obs-preeclampsia-mx'),
  ('UKMLA', ARRAY['Obstetrics','Miscarriage'],
   'Miscarriage management options after USS-confirmed: expectant (1-2 weeks), medical (misoprostol), or surgical (manual vacuum aspiration / SMM).',
   'A 30-year-old at 9/40 has confirmed missed miscarriage on USS. She is haemodynamically stable. First-line option to discuss?',
   'Expectant management for 1-2 weeks unless there is heavy bleeding, infection, or a previous miscarriage',
   '["Immediate surgical evacuation","IV oxytocin alone","Hysterectomy","Mifepristone alone — no misoprostol needed"]'::jsonb,
   2, null, null, 'https://www.nice.org.uk/guidance/ng126', 'NICE NG126 — Miscarriage', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-obs-miscarriage-mx'),
  ('UKMLA', ARRAY['Obstetrics','Anti-D'],
   'Anti-D for RhD-negative women: prophylaxis at 28 weeks (single 1500 IU dose), and within 72 h of any sensitising event (delivery, bleeding, trauma, ECV).',
   'A 28/40 RhD-negative woman with no sensitising events. Most appropriate routine intervention?',
   'Anti-D 1500 IU IM as routine antenatal prophylaxis',
   '["Anti-D only if Kleihauer test positive","No anti-D — only used after delivery","Folic acid 5 mg daily","IV ferritin infusion"]'::jsonb,
   2, null, null, 'https://www.nice.org.uk/guidance/ta156', 'NICE TA156 — Anti-D for RhD-neg', 'doctor_seed',
   true, true, 'pending_review', 'sba', 'sba-obs-antid-routine')
) as new_rows (
  exam, topic_path, claim, canonical_stem, answer, distractors,
  difficulty, image_url, image_alt,
  citation_url, citation_label, source_type,
  high_yield, free_tier, status, question_kind, source_concept_id
)
where not exists (
  select 1 from public.atoms a where a.source_concept_id = new_rows.source_concept_id
);
